version: '3'

services:
  scouting-db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: scouting
      MYSQL_ROOT_PASSWORD: scouting
      MYSQL_PASSWORD: scouting
      MYSQL_USER: scouting
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: scouting
    external_links:
      - scouting-db:db

