spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scouting
    username: scouting
    password: scouting
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

---
spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: update