spring:
  datasource:
    url: jdbc:h2:./build/database/scouting;AUTO_SERVER=TRUE
    username: scouting
    password: scouting
  h2:
    console:
      enabled: true
      path: /h2
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
