INSERT INTO users (username, password, enabled)
VALUES ('admin', '$2a$10$9ALpT96a4IAOBZ1BVnorKupnhCE6GM5VF3WHhKxAv402PX5NX4Gw2', TRUE),
  ('user', '$2a$10$t9Ebz8953gdqmB464K0RJ.vVe1.ZHu5P6l.k3W8oLDVx0me47qEg2', TRUE);

INSERT INTO authorities (username, authority)
VALUES ('admin', 'ROLE_ADMIN'),
  ('admin', 'ROLE_USER'),
  ('user', 'ROLE_USER');
  
INSERT INTO TEAM (TEAM_NUMBER, TEAM_NAME) VALUES
(1, 'The Juggernauts'),
(8, 'Team 8'),
(25, 'Raider Robotix'),
(166, 'Chop Shop'),
(191, 'X-CATS'),
(238, 'Cruisin'' Crusaders'),
(287, 'Floyd'),
(321, 'RoboLancers'),
(339, 'Kilroy Robotics'),
(379, 'RoboCats'),
(422, 'Mech Tech Dragons'),
(435, 'Robodogs'),
(587, 'Hedgehogs'),
(639, 'Code Red Robotics'),
(694, 'StuyPulse'),
(836, 'The RoboBees'),
(858, 'Demons'),
(876, 'Thunder Robotics'),
(900, 'â™žThe Zebracornsâ™ž'),
(955, 'CV Robotics'),
(1073, 'The Force Team'),
(1089, 'Team Mercury'),
(1123, 'AIM Robotics'),
(1225, 'Gorillas'),
(1261, 'Robo  Lions'),
(1389, 'The Body Electric'),
(1511, 'Rolling Thunder'),
(1533, 'Triple Strange'),
(1600, 'ROBO KINGS AND QUEENS'),
(1662, 'Raptor Force Engineering'),
(1868, 'Space Cookies'),
(1885, 'ILITE Robotics'),
(1983, 'Skunk Works Robotics'),
(1991, 'Dragons'),
(2059, 'The Hitchhikers'),
(2080, 'Torbotics'),
(2168, 'Aluminum Falcons'),
(2175, 'The Fighting Calculators'),
(2219, 'Megahurts'),
(2220, 'Blue Twilight'),
(2557, 'SOTAbots'),
(2640, 'HOTBOTZ'),
(2642, 'Pitt Pirates'),
(2655, 'The Flying Platypi'),
(2682, 'Boneyard Robotics'),
(2848, 'The All Sparks'),
(2883, 'F.R.E.D (Fighting Rednecks Engineering and Design)'),
(2974, 'Walton Robotics'),
(2980, 'The Whidbey Island Wild Cats'),
(3005, 'RoboChargers'),
(3147, 'Munster HorsePower'),
(3196, 'Team SPORK'),
(3197, 'HexHounds'),
(3229, 'Hawktimus Prime'),
(3230, 'PrototypeX'),
(3234, 'Red Arrows'),
(3310, 'Black Hawk Robotics'),
(3336, 'Zimanators'),
(3339, 'BumbleB'),
(3374, 'RoboBroncs'),
(3402, 'ROBOMonkeys'),
(3459, 'Team PyroTech'),
(3506, 'YETI Robotics'),
(3546, 'Buc''n''Gears'),
(3618, 'Petoskey Paladins'),
(3641, 'The Flying Toasters'),
(3656, 'Dreadbots'),
(3661, 'RoboWolves'),
(3680, 'Elemental Dragons'),
(3737, 'Roto-Raptors'),
(3763, '4-H WildCards'),
(3770, 'BlitzCreek'),
(3822, 'Neon Jets'),
(3845, 'Yellow Jackets'),
(3925, 'Circuit of Life'),
(3930, 'SMART  Spruce Mountain Area Robotics Team'),
(3965, 'Sultans'),
(3971, 'Kai Orbus'),
(3990, 'Tech for Kids'),
(4010, 'Nautilus'),
(4061, 'SciBorgs'),
(4087, 'Falcon Robotics'),
(4180, 'Iron Riders'),
(4188, 'Columbus Space Program'),
(4290, 'Bots of War'),
(4291, 'KerrBots (pronounced CarBots)'),
(4329, 'Lutheran Roboteers'),
(4335, 'Metallic Clouds'),
(4455, 'The Burger Bots'),
(4469, 'R.A.I.D. (Raider Artificial Intelligence DIvision)'),
(4534, 'Wired Wizards'),
(4561, 'TerrorBytes'),
(4646, 'Team ASAP'),
(4767, 'C4'),
(4795, 'EastBots'),
(4816, 'Gadget Girls'),
(4828, 'RoboEagles'),
(4829, 'Titanium Tigers'),
(4910, 'East Cobb Robotics'),
(4929, 'Maroon Monsoon'),
(4935, 'T-Rex'),
(5160, 'Chargers'),
(5190, 'Green Hope Falcons'),
(5199, 'Robot Dolphins From Outer Space'),
(5279, 'Bionic Eagles'),
(5406, 'Celt-X'),
(5446, 'Pink Detectives'),
(5511, 'Cortechs Robotics'),
(5518, 'Techno Wolves'),
(5544, 'SWIFT Robotics'),
(5607, 'Team Firewall'),
(5679, 'Girls on Fire'),
(5727, 'REaCH Omegabytes'),
(5762, 'Franklinbots'),
(5803, 'Apex Robotics'),
(5834, 'R3P2'),
(5837, 'Unity4Tech'),
(5854, 'GLITCH'),
(5892, 'High Energy'),
(5919, 'JoCo RoBos'),
(5933, 'JudgeMent Call'),
(5940, 'B.R.E.A.D.'),
(5976, 'CyberSaders'),
(5979, 'Apex'),
(6003, 'S.U.M. (Singularly Unified Madness)'),
(6004, 'f(x) Robotics'),
(6016, 'Tiger Robotics'),
(6034, 'Eagle Storms'),
(6214, 'Los Creadores'),
(6215, 'Armored Eagles'),
(6332, 'Bull City Botics'),
(6500, 'GearCats'),
(6502, 'DARC SIDE'),
(6565, 'Team Bobcat'),
(6639, 'Mechanical Minds'),
(6729, 'RECHS Ea' );

insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit', false, true, 1, false, 1, 1, false, 83, 2, 3, 6, 6, 7, 1, 5, 639, 3, 7, 3, 0);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc', true, true, 2, true, 1, 3, true, 22, 2, 2, 2, 7, 5, 0, 37, 6565, 6, 7, 2, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet', false, false, 0, true, 3, 2, false, 64, 1, 3, 5, 1, 2, 1, 68, 1261, 3, 1, 4, 7);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'quis libero nullam sit amet turpis elementum ligula vehicula consequat', false, true, 1, true, 1, 1, true, 34, 1, 1, 4, 4, 0, 7, 20, 1533, 2, 4, 3, 4);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus', false, false, 2, false, 1, 3, true, 37, 2, 2, 1, 0, 6, 7, 41, 5544, 0, 2, 4, 3);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'donec semper sapien a libero nam dui proin leo odio porttitor id consequat in', true, true, 3, true, 3, 1, true, 83, 1, 2, 2, 0, 3, 4, 14, 6034, 2, 1, 0, 2);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo', true, true, 5, true, 1, 2, true, 84, 3, 1, 5, 3, 2, 7, 40, 6214, 5, 2, 3, 3);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea', false, true, 6, false, 2, 3, false, 68, 1, 1, 1, 7, 1, 1, 87, 3971, 0, 4, 2, 7);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'quam pede lobortis ligula sit amet eleifend pede libero quis', true, true, 1, true, 2, 2, true, 51, 2, 2, 6, 2, 6, 4, 5, 3310, 6, 6, 5, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie', false, false, 0, true, 1, 2, false, 83, 2, 3, 7, 7, 7, 4, 46, 1123, 3, 3, 1, 3);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan', true, true, 1, true, 2, 3, false, 37, 3, 3, 0, 0, 2, 0, 68, 3402, 6, 6, 3, 1);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus', false, false, 0, true, 3, 3, false, 53, 3, 3, 1, 5, 1, 4, 83, 5919, 4, 4, 0, 2);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc', false, true, 6, false, 1, 2, false, 96, 3, 3, 6, 3, 0, 2, 58, 3402, 6, 0, 5, 0);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur', false, false, 2, true, 2, 1, true, 28, 1, 3, 4, 3, 0, 4, 83, 5933, 0, 1, 5, 0);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus', false, false, 3, true, 1, 1, false, 44, 2, 2, 2, 7, 6, 6, 4, 5446, 1, 2, 3, 1);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet', false, true, 1, true, 3, 2, true, 61, 2, 2, 4, 1, 0, 3, 52, 1225, 0, 7, 6, 4);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean', true, true, 0, true, 1, 3, false, 37, 2, 1, 2, 2, 0, 4, 61, 5919, 6, 1, 3, 4);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non', false, false, 3, true, 3, 3, false, 46, 1, 3, 4, 5, 6, 5, 44, 1261, 7, 1, 1, 0);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis', false, false, 6, false, 2, 2, true, 88, 3, 1, 7, 1, 7, 5, 45, 287, 4, 5, 2, 2);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus', false, true, 5, true, 1, 3, true, 63, 3, 2, 2, 6, 4, 4, 30, 1533, 1, 1, 0, 2);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum', false, false, 7, true, 2, 1, true, 65, 3, 2, 4, 1, 7, 0, 70, 4828, 2, 3, 7, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui', false, true, 5, true, 1, 1, false, 3, 2, 1, 1, 0, 4, 6, 13, 2980, 5, 5, 2, 7);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales', true, false, 3, true, 3, 1, true, 98, 2, 2, 5, 3, 2, 2, 77, 3925, 0, 1, 2, 2);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat', false, true, 3, true, 3, 1, false, 85, 3, 2, 5, 3, 1, 4, 45, 3965, 7, 3, 0, 3);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus', true, true, 7, true, 2, 1, false, 71, 1, 3, 6, 5, 2, 4, 52, 4335, 3, 0, 3, 3);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel', false, true, 5, true, 1, 3, false, 23, 3, 2, 0, 0, 4, 1, 48, 3680, 0, 0, 0, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', false, false, 3, true, 1, 3, false, 91, 3, 3, 6, 0, 3, 3, 14, 3197, 7, 5, 5, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum', true, false, 2, false, 3, 3, false, 20, 1, 2, 4, 0, 3, 4, 92, 1868, 0, 5, 2, 0);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla', false, false, 3, false, 3, 2, true, 97, 3, 2, 0, 4, 0, 3, 69, 6565, 5, 7, 5, 3);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse', true, false, 4, true, 1, 3, false, 86, 2, 1, 5, 7, 6, 2, 100, 3618, 5, 3, 7, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at', false, false, 7, true, 3, 1, true, 9, 3, 2, 4, 4, 4, 5, 64, 5892, 6, 0, 7, 7);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam', false, true, 2, true, 2, 1, false, 95, 2, 3, 5, 6, 0, 1, 7, 4290, 7, 0, 2, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'tortor duis mattis egestas metus aenean fermentum donec ut mauris', true, true, 3, true, 1, 1, true, 68, 1, 2, 4, 0, 6, 5, 3, 5834, 7, 1, 6, 0);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque', true, false, 0, false, 3, 1, false, 24, 3, 2, 7, 7, 5, 4, 95, 5762, 6, 2, 0, 1);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id', true, true, 1, true, 1, 1, true, 63, 1, 3, 0, 5, 3, 6, 90, 4010, 7, 2, 3, 6);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis', true, true, 3, true, 2, 1, true, 42, 2, 3, 2, 2, 2, 5, 36, 1123, 7, 3, 4, 4);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', true, true, 3, true, 3, 2, true, 77, 2, 1, 5, 5, 7, 5, 32, 3506, 7, 7, 1, 4);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam', false, false, 4, false, 1, 2, true, 50, 1, 2, 2, 5, 1, 2, 45, 4291, 4, 2, 4, 7);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'augue aliquam erat volutpat in congue etiam justo etiam pretium', true, false, 5, true, 3, 1, true, 49, 3, 1, 1, 2, 4, 3, 32, 25, 4, 0, 6, 1);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat', true, false, 3, false, 3, 3, true, 88, 2, 1, 7, 1, 1, 5, 2, 3618, 3, 5, 2, 6);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam', false, true, 4, false, 3, 1, false, 73, 3, 2, 5, 1, 5, 1, 73, 4469, 7, 6, 4, 6);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo', true, false, 0, true, 2, 1, false, 52, 1, 3, 2, 0, 7, 0, 52, 4469, 5, 0, 1, 1);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', true, false, 2, false, 1, 3, true, 57, 3, 3, 3, 7, 0, 1, 70, 1089, 4, 1, 0, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut', true, true, 7, true, 1, 3, true, 1, 3, 1, 7, 5, 1, 3, 94, 6639, 2, 5, 7, 4);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam', false, true, 5, false, 1, 1, false, 12, 2, 2, 5, 3, 1, 3, 1, 2168, 2, 4, 2, 2);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis', true, false, 1, true, 2, 2, true, 38, 1, 1, 3, 6, 3, 0, 73, 4180, 5, 4, 7, 1);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus', false, true, 4, false, 2, 1, false, 53, 1, 2, 6, 7, 1, 5, 11, 4829, 5, 5, 2, 2);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem', true, false, 0, true, 2, 2, true, 48, 3, 3, 1, 7, 2, 0, 36, 4829, 0, 6, 5, 0);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a', false, true, 5, false, 3, 1, false, 48, 1, 3, 0, 7, 3, 7, 32, 4180, 6, 2, 7, 1);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec', true, true, 4, true, 2, 1, true, 96, 3, 3, 3, 7, 2, 5, 34, 3234, 5, 6, 1, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue', true, true, 0, false, 1, 2, true, 79, 1, 3, 4, 3, 2, 2, 86, 4290, 1, 0, 1, 7);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'molestie sed justo pellentesque viverra pede ac diam cras pellentesque', false, true, 2, false, 2, 2, false, 10, 2, 3, 4, 1, 3, 3, 16, 5803, 2, 6, 6, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa', true, true, 7, true, 3, 1, false, 40, 1, 1, 1, 2, 1, 0, 63, 3230, 7, 6, 6, 2);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget', true, false, 7, true, 1, 1, true, 71, 2, 2, 0, 2, 6, 3, 32, 2175, 4, 4, 1, 7);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur', false, false, 2, true, 2, 1, true, 88, 3, 2, 3, 5, 1, 1, 57, 3197, 0, 3, 0, 1);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit', false, false, 2, true, 1, 3, true, 61, 1, 1, 5, 7, 0, 5, 70, 1868, 6, 4, 3, 4);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel', true, true, 1, true, 2, 1, true, 73, 1, 2, 6, 5, 6, 1, 85, 5803, 5, 5, 3, 1);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula', true, false, 2, true, 1, 1, false, 77, 2, 1, 3, 7, 0, 1, 5, 3661, 4, 5, 7, 3);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'non sodales sed tincidunt eu felis fusce posuere felis sed', true, true, 6, false, 3, 3, true, 58, 1, 1, 7, 1, 6, 2, 99, 4829, 1, 4, 3, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut', false, true, 5, false, 3, 3, false, 58, 2, 3, 1, 4, 1, 6, 28, 5837, 3, 5, 5, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'in faucibus orci luctus et ultrices posuere cubilia curae donec', true, true, 1, false, 3, 2, false, 93, 3, 1, 2, 0, 5, 5, 85, 3197, 3, 6, 2, 0);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo', true, false, 4, true, 2, 3, false, 54, 2, 2, 4, 2, 5, 3, 35, 1868, 4, 1, 4, 0);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate', true, true, 3, true, 1, 3, true, 8, 3, 3, 2, 6, 2, 0, 98, 5979, 0, 4, 6, 4);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede', false, false, 7, false, 2, 3, true, 78, 1, 2, 4, 1, 3, 2, 22, 5511, 1, 5, 0, 1);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus', true, true, 2, true, 2, 3, false, 31, 3, 3, 2, 0, 5, 0, 60, 2974, 0, 7, 4, 3);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus', true, true, 5, true, 3, 2, false, 57, 2, 3, 5, 4, 7, 5, 22, 6565, 7, 2, 2, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', true, true, 6, false, 1, 1, true, 64, 2, 1, 4, 4, 4, 4, 57, 191, 0, 1, 5, 7);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum', false, false, 2, false, 2, 2, true, 91, 3, 2, 7, 6, 2, 0, 28, 5762, 7, 7, 1, 7);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit', true, true, 5, false, 1, 2, true, 62, 3, 1, 7, 2, 2, 4, 82, 5892, 5, 6, 1, 6);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien', true, false, 4, true, 3, 3, true, 90, 2, 2, 1, 3, 4, 5, 58, 5940, 5, 5, 6, 2);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', true, true, 2, false, 2, 2, false, 72, 1, 2, 5, 7, 2, 6, 73, 4087, 1, 0, 7, 6);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus', false, false, 7, false, 2, 2, true, 22, 3, 3, 2, 3, 7, 7, 31, 5190, 0, 3, 2, 6);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'in felis donec semper sapien a libero nam dui proin leo', true, false, 6, false, 3, 3, true, 97, 2, 3, 4, 6, 3, 5, 19, 3310, 2, 6, 5, 2);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'morbi odio odio elementum eu interdum eu tincidunt in leo maecenas', false, true, 6, false, 2, 1, true, 31, 2, 1, 2, 6, 6, 2, 31, 3310, 1, 0, 5, 3);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in', false, true, 0, false, 1, 2, true, 38, 1, 3, 3, 7, 0, 4, 92, 1261, 3, 7, 1, 7);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis', false, false, 5, true, 3, 1, true, 53, 1, 3, 1, 6, 2, 2, 86, 6003, 0, 6, 6, 3);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien', false, false, 1, true, 2, 1, true, 51, 3, 2, 0, 5, 2, 0, 34, 2557, 0, 0, 1, 4);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'luctus et ultrices posuere cubilia curae duis faucibus accumsan odio', true, true, 6, true, 3, 1, true, 98, 2, 3, 1, 0, 3, 0, 21, 1, 3, 1, 3, 4);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor', true, false, 4, true, 3, 3, false, 63, 1, 2, 6, 1, 3, 4, 30, 3197, 4, 4, 7, 4);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'felis ut at dolor quis odio consequat varius integer ac leo', true, false, 3, true, 3, 2, false, 17, 1, 3, 2, 6, 3, 3, 34, 836, 0, 6, 5, 1);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices', false, true, 2, false, 2, 1, false, 76, 1, 3, 4, 1, 2, 4, 22, 587, 5, 0, 5, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed', true, false, 0, true, 2, 2, true, 79, 1, 2, 0, 0, 7, 3, 25, 4910, 0, 2, 3, 0);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula', true, true, 3, false, 2, 1, false, 5, 1, 1, 4, 4, 0, 3, 17, 2168, 2, 2, 0, 0);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla', true, true, 4, false, 3, 1, true, 82, 1, 3, 6, 3, 6, 3, 20, 5919, 3, 7, 1, 4);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam', false, true, 4, true, 1, 2, true, 54, 2, 1, 4, 7, 4, 5, 68, 1662, 6, 4, 7, 2);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed', false, false, 4, false, 3, 2, false, 89, 2, 1, 7, 5, 3, 0, 28, 4910, 0, 6, 7, 4);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula', true, false, 6, false, 2, 2, false, 43, 1, 2, 1, 0, 0, 6, 1, 1600, 1, 2, 7, 7);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', false, true, 0, false, 3, 3, true, 94, 3, 3, 0, 6, 6, 2, 57, 5199, 5, 5, 5, 6);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla', true, false, 5, false, 3, 1, true, 92, 1, 3, 7, 6, 6, 2, 34, 858, 2, 1, 6, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum', false, false, 5, true, 3, 2, false, 80, 3, 1, 4, 2, 5, 2, 17, 4455, 0, 6, 5, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper', false, true, 3, false, 3, 3, true, 61, 1, 1, 5, 6, 5, 4, 44, 639, 6, 4, 0, 4);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus', true, true, 3, true, 2, 2, false, 49, 3, 2, 0, 4, 6, 7, 58, 2883, 5, 3, 4, 1);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis', false, true, 4, false, 1, 2, false, 95, 2, 1, 3, 1, 7, 3, 38, 639, 7, 4, 5, 7);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci', false, false, 7, false, 2, 3, true, 67, 1, 1, 7, 1, 3, 5, 10, 3336, 5, 0, 1, 3);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor', false, true, 1, false, 3, 1, true, 12, 1, 3, 4, 0, 5, 6, 16, 858, 0, 3, 6, 1);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor', false, true, 5, true, 2, 3, false, 82, 1, 1, 5, 2, 3, 6, 51, 2642, 4, 7, 7, 1);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et', false, false, 2, false, 3, 1, true, 60, 3, 3, 2, 6, 1, 2, 40, 2655, 6, 7, 4, 5);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan', false, true, 5, true, 2, 1, false, 69, 1, 2, 0, 3, 0, 5, 37, 4561, 2, 4, 7, 0);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', true, 'mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec', false, false, 1, false, 1, 2, true, 98, 3, 2, 2, 7, 1, 6, 45, 4646, 0, 4, 4, 3);
insert into scouting_form (scouter, buddy_climb, comment, cross_habitat_line, defense, dropped_game_pieces, got_lifted, hab_level_climb, hab_level_start, lifted, match_number, preload, rocket_level, sandstorm_cargo_ball_count, sandstorm_cargo_hatch_panel_count, sandstorm_rocket_ball_count, sandstorm_rocket_hatch_panel_count, score, team_number, teleop_cargo_ball_count, teleop_cargo_hatch_panel_count, teleop_rocket_ball_count, teleop_rocket_hatch_panel_count) values ('user', false, 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi', true, false, 6, false, 1, 2, false, 33, 2, 2, 4, 7, 3, 5, 8, 4534, 6, 7, 2, 0);