INSERT INTO TEAM (TEAM_NUMBER, TEAM_NAME) VALUES
(1, 'The Juggernauts'),
(8, 'Team 8'),
(25, 'Raider Robotix'),
(166, 'Chop Shop'),
(191, 'X-CATS'),
(238, 'Cruisin'' Crusaders'),
(287, 'Floyd'),
(321, 'RoboLancers'),
(339, 'Kilroy Robotics'),
(379, 'RoboCats'),
(422, 'Mech Tech Dragons'),
(435, 'Robodogs'),
(587, 'Hedgehogs'),
(639, 'Code Red Robotics'),
(694, 'StuyPulse'),
(836, 'The RoboBees'),
(858, 'Demons'),
(876, 'Thunder Robotics'),
(900, 'â™žThe Zebracornsâ™ž'),
(955, 'CV Robotics'),
(1073, 'The Force Team'),
(1089, 'Team Mercury'),
(1123, 'AIM Robotics'),
(1225, 'Gorillas'),
(1261, 'Robo  Lions'),
(1389, 'The Body Electric'),
(1511, 'Rolling Thunder'),
(1533, 'Triple Strange'),
(1600, 'ROBO KINGS AND QUEENS'),
(1662, 'Raptor Force Engineering'),
(1868, 'Space Cookies'),
(1885, 'ILITE Robotics'),
(1983, 'Skunk Works Robotics'),
(1991, 'Dragons'),
(2059, 'The Hitchhikers'),
(2080, 'Torbotics'),
(2168, 'Aluminum Falcons'),
(2175, 'The Fighting Calculators'),
(2219, 'Megahurts'),
(2220, 'Blue Twilight'),
(2557, 'SOTAbots'),
(2640, 'HOTBOTZ'),
(2642, 'Pitt Pirates'),
(2655, 'The Flying Platypi'),
(2682, 'Boneyard Robotics'),
(2848, 'The All Sparks'),
(2883, 'F.R.E.D (Fighting Rednecks Engineering and Design)'),
(2974, 'Walton Robotics'),
(2980, 'The Whidbey Island Wild Cats'),
(3005, 'RoboChargers'),
(3147, 'Munster HorsePower'),
(3196, 'Team SPORK'),
(3197, 'HexHounds'),
(3229, 'Hawktimus Prime'),
(3230, 'PrototypeX'),
(3234, 'Red Arrows'),
(3310, 'Black Hawk Robotics'),
(3336, 'Zimanators'),
(3339, 'BumbleB'),
(3374, 'RoboBroncs'),
(3402, 'ROBOMonkeys'),
(3459, 'Team PyroTech'),
(3506, 'YETI Robotics'),
(3546, 'Buc''n''Gears'),
(3618, 'Petoskey Paladins'),
(3641, 'The Flying Toasters'),
(3656, 'Dreadbots'),
(3661, 'RoboWolves'),
(3680, 'Elemental Dragons'),
(3737, 'Roto-Raptors'),
(3763, '4-H WildCards'),
(3770, 'BlitzCreek'),
(3822, 'Neon Jets'),
(3845, 'Yellow Jackets'),
(3925, 'Circuit of Life'),
(3930, 'SMART  Spruce Mountain Area Robotics Team'),
(3965, 'Sultans'),
(3971, 'Kai Orbus'),
(3990, 'Tech for Kids'),
(4010, 'Nautilus'),
(4061, 'SciBorgs'),
(4087, 'Falcon Robotics'),
(4180, 'Iron Riders'),
(4188, 'Columbus Space Program'),
(4290, 'Bots of War'),
(4291, 'KerrBots (pronounced CarBots)'),
(4329, 'Lutheran Roboteers'),
(4335, 'Metallic Clouds'),
(4455, 'The Burger Bots'),
(4469, 'R.A.I.D. (Raider Artificial Intelligence DIvision)'),
(4534, 'Wired Wizards'),
(4561, 'TerrorBytes'),
(4646, 'Team ASAP'),
(4767, 'C4'),
(4795, 'EastBots'),
(4816, 'Gadget Girls'),
(4828, 'RoboEagles'),
(4829, 'Titanium Tigers'),
(4910, 'East Cobb Robotics'),
(4929, 'Maroon Monsoon'),
(4935, 'T-Rex'),
(5160, 'Chargers'),
(5190, 'Green Hope Falcons'),
(5199, 'Robot Dolphins From Outer Space'),
(5279, 'Bionic Eagles'),
(5406, 'Celt-X'),
(5446, 'Pink Detectives'),
(5511, 'Cortechs Robotics'),
(5518, 'Techno Wolves'),
(5544, 'SWIFT Robotics'),
(5607, 'Team Firewall'),
(5679, 'Girls on Fire'),
(5727, 'REaCH Omegabytes'),
(5762, 'Franklinbots'),
(5803, 'Apex Robotics'),
(5834, 'R3P2'),
(5837, 'Unity4Tech'),
(5854, 'GLITCH'),
(5892, 'High Energy'),
(5919, 'JoCo RoBos'),
(5933, 'JudgeMent Call'),
(5940, 'B.R.E.A.D.'),
(5976, 'CyberSaders'),
(5979, 'Apex'),
(6003, 'S.U.M. (Singularly Unified Madness)'),
(6004, 'f(x) Robotics'),
(6016, 'Tiger Robotics'),
(6034, 'Eagle Storms'),
(6214, 'Los Creadores'),
(6215, 'Armored Eagles'),
(6332, 'Bull City Botics'),
(6500, 'GearCats'),
(6502, 'DARC SIDE'),
(6565, 'Team Bobcat'),
(6639, 'Mechanical Minds'),
(6729, 'RECHS Ea' );

insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (1, 73, 7442, false, 1, 3, 3, 1, 3, 1, 3, 5, 4, 'proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor', 246, 1, true, 2, true, false, true, 14);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (2, 31, 2945, false, 1, 2, 1, 2, 1, 4, 2, 10, 8, 'lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in', 157, 3, false, 1, false, false, false, 2);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (3, 85, 523, true, 2, 2, 2, 1, 1, 6, 1, 9, 3, 'justo aliquam quis turpis eget elit sodales scelerisque mauris sit', 277, 0, true, 0, true, false, true, 11);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (4, 43, 8885, true, 2, 1, 2, 1, 1, 4, 7, 2, 3, 'est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in', 73, 3, false, 1, false, true, true, 9);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (5, 14, 7807, false, 1, 3, 2, 3, 3, 7, 5, 10, 5, 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum', 282, 0, true, 0, false, true, true, 6);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (6, 65, 1893, true, 1, 3, 3, 3, 2, 8, 8, 7, 9, 'tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum', 155, 3, true, 0, false, true, true, 6);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (7, 66, 3874, false, 1, 3, 2, 2, 1, 4, 4, 2, 2, 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend', 1, 2, true, 2, false, false, true, 11);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (8, 71, 9769, true, 1, 2, 1, 3, 3, 6, 2, 4, 6, 'donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', 255, 0, true, 0, false, false, true, 3);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (9, 72, 7633, true, 2, 3, 3, 1, 1, 7, 3, 10, 4, 'lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in', 76, 3, false, 1, true, true, false, 7);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (10, 11, 7614, false, 2, 1, 3, 3, 2, 1, 3, 7, 12, 'ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 281, 0, false, 1, true, false, false, 12);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (11, 55, 3807, true, 1, 2, 2, 3, 2, 3, 5, 9, 12, 'eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis', 234, 1, true, 2, false, false, true, 13);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (12, 76, 628, true, 2, 2, 1, 2, 2, 6, 7, 6, 11, 'dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 154, 3, true, 0, false, false, true, 1);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (13, 21, 8731, false, 2, 3, 1, 1, 2, 6, 2, 12, 7, 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis', 271, 0, false, 2, true, true, true, 14);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (14, 30, 3310, true, 2, 2, 3, 2, 1, 7, 7, 10, 3, 'in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam', 125, 3, false, 0, true, true, true, 9);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (15, 80, 2712, false, 1, 3, 1, 3, 1, 6, 8, 2, 8, 'felis ut at dolor quis odio consequat varius integer ac leo pellentesque', 202, 1, false, 2, true, true, false, 5);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (16, 22, 7652, true, 2, 1, 2, 1, 1, 2, 1, 9, 9, 'leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', 283, 2, false, 2, false, true, true, 11);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (17, 54, 9305, true, 2, 1, 3, 1, 2, 7, 8, 6, 8, 'pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie', 115, 2, true, 1, false, true, true, 7);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (18, 49, 9458, true, 2, 1, 2, 2, 3, 3, 3, 11, 3, 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin', 152, 1, false, 0, false, true, false, 15);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (19, 39, 9960, false, 2, 3, 3, 1, 1, 1, 1, 2, 12, 'bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus', 110, 1, true, 0, false, false, true, 8);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (20, 80, 5507, true, 2, 1, 3, 3, 1, 1, 8, 4, 9, 'velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien', 132, 0, false, 2, true, false, true, 1);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (21, 100, 797, false, 1, 3, 1, 1, 3, 4, 2, 9, 8, 'eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum', 23, 2, false, 1, true, true, false, 12);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (22, 22, 9447, false, 2, 1, 3, 3, 1, 4, 6, 4, 11, 'id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus', 270, 0, false, 1, false, true, true, 6);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (23, 58, 6813, false, 2, 1, 1, 1, 1, 8, 4, 3, 6, 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et', 75, 1, true, 0, true, false, false, 8);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (24, 36, 7513, true, 1, 1, 2, 1, 1, 4, 8, 9, 4, 'turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at', 233, 0, false, 0, true, false, true, 9);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (25, 97, 7942, true, 2, 2, 1, 1, 2, 1, 6, 9, 2, 'sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat', 147, 1, false, 2, false, true, false, 13);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (26, 61, 2224, false, 1, 1, 3, 2, 2, 6, 5, 7, 9, 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio', 156, 3, true, 2, true, false, false, 5);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (27, 49, 4709, false, 1, 1, 3, 1, 1, 1, 6, 9, 9, 'libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed', 208, 3, false, 2, false, true, true, 6);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (28, 81, 8765, true, 2, 1, 3, 1, 1, 2, 1, 10, 3, 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient', 151, 0, false, 0, false, true, false, 4);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (29, 24, 5372, true, 2, 3, 3, 1, 2, 6, 5, 8, 7, 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem', 66, 1, false, 0, false, false, false, 9);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (30, 38, 9514, true, 1, 3, 1, 3, 2, 3, 7, 1, 12, 'consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi', 47, 0, false, 1, false, true, true, 15);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (31, 61, 6020, false, 2, 3, 1, 2, 3, 6, 6, 11, 10, 'lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere', 68, 3, false, 0, false, true, false, 13);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (32, 79, 9675, false, 2, 1, 1, 2, 3, 1, 3, 2, 6, 'duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec', 197, 1, true, 0, true, true, false, 14);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (33, 70, 1230, true, 1, 1, 3, 2, 3, 4, 2, 3, 6, 'quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat', 103, 0, false, 1, true, true, false, 1);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (34, 48, 1844, true, 2, 1, 2, 2, 1, 6, 5, 11, 6, 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis', 277, 1, false, 2, false, true, false, 2);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (35, 32, 554, false, 1, 3, 2, 1, 1, 5, 7, 8, 2, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus', 231, 0, false, 1, false, false, false, 14);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (36, 23, 1844, true, 2, 1, 2, 3, 1, 6, 1, 7, 6, 'mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem', 181, 0, false, 2, false, true, true, 4);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (37, 22, 2900, true, 1, 3, 2, 2, 3, 8, 7, 9, 7, 'vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in', 56, 0, false, 0, false, false, true, 11);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (38, 1, 3733, false, 1, 1, 2, 3, 2, 1, 8, 6, 12, 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat', 256, 1, false, 1, true, false, true, 13);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (39, 34, 5017, false, 1, 1, 1, 1, 2, 3, 3, 8, 1, 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida', 6, 1, true, 0, true, true, true, 3);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (40, 4, 5463, true, 2, 2, 2, 1, 3, 5, 3, 6, 10, 'magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id', 228, 1, false, 1, true, true, true, 13);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (41, 43, 7905, false, 1, 3, 2, 2, 1, 2, 2, 6, 4, 'adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien', 137, 1, true, 1, false, true, true, 12);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (42, 57, 1293, true, 2, 2, 2, 1, 1, 7, 1, 12, 7, 'at turpis a pede posuere nonummy integer non velit donec', 43, 0, true, 0, true, true, true, 2);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (43, 11, 5356, true, 1, 2, 1, 2, 3, 1, 4, 12, 11, 'venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu', 76, 1, true, 0, false, true, false, 5);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (44, 19, 617, true, 2, 2, 2, 3, 1, 1, 4, 1, 11, 'ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui', 55, 3, false, 1, true, true, false, 2);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (45, 86, 6379, true, 2, 1, 1, 1, 3, 6, 6, 5, 3, 'fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id', 144, 3, false, 1, false, true, false, 3);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (46, 31, 6189, false, 2, 1, 2, 3, 3, 7, 3, 8, 3, 'et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo', 84, 3, false, 2, true, false, false, 15);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (47, 1, 5497, false, 2, 2, 3, 2, 3, 8, 3, 9, 11, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra', 106, 0, false, 0, true, true, true, 14);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (48, 14, 9341, false, 1, 3, 2, 2, 2, 5, 3, 11, 4, 'lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea', 26, 2, true, 0, true, false, true, 10);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (49, 3, 9459, true, 1, 3, 1, 2, 2, 8, 3, 3, 9, 'vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet', 157, 3, false, 1, false, true, false, 5);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (50, 63, 7553, false, 1, 1, 3, 2, 2, 6, 4, 5, 12, 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices', 177, 3, true, 2, false, false, true, 1);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (51, 2, 7991, true, 2, 1, 2, 2, 1, 1, 8, 9, 7, 'in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio', 137, 1, true, 0, true, false, true, 15);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (52, 9, 965, false, 1, 1, 3, 2, 2, 2, 1, 8, 12, 'nibh in lectus pellentesque at nulla suspendisse potenti cras in purus', 187, 1, true, 1, true, true, false, 13);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (53, 22, 4791, true, 1, 2, 1, 3, 3, 7, 1, 7, 1, 'libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac', 276, 0, false, 2, false, true, false, 15);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (54, 31, 3522, true, 1, 1, 2, 2, 3, 6, 5, 6, 6, 'hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent', 300, 3, true, 2, true, true, true, 2);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (55, 99, 3145, false, 2, 3, 2, 2, 3, 8, 2, 2, 5, 'nisl aenean lectus pellentesque eget nunc donec quis orci eget orci', 27, 3, false, 2, true, true, true, 8);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (56, 87, 2775, true, 1, 2, 3, 2, 3, 6, 1, 11, 7, 'nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros', 169, 0, true, 0, true, false, true, 15);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (57, 46, 8357, false, 1, 3, 3, 3, 3, 1, 8, 5, 5, 'ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel', 125, 0, false, 1, false, true, false, 10);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (58, 17, 279, false, 2, 1, 2, 2, 3, 1, 6, 5, 7, 'tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam', 189, 2, true, 2, false, true, true, 9);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (59, 11, 1945, false, 1, 3, 1, 2, 1, 3, 6, 11, 11, 'sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', 219, 2, false, 2, true, true, false, 6);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (60, 26, 6533, true, 1, 3, 2, 2, 2, 3, 6, 8, 4, 'mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim', 268, 0, true, 1, true, false, false, 1);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (61, 37, 1769, false, 1, 3, 2, 2, 1, 5, 3, 8, 12, 'quam a odio in hac habitasse platea dictumst maecenas ut', 260, 3, true, 2, false, true, false, 11);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (62, 40, 5352, false, 1, 3, 1, 2, 2, 5, 4, 7, 7, 'iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat', 112, 1, false, 1, false, true, true, 11);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (63, 92, 2413, true, 1, 2, 1, 1, 2, 6, 7, 9, 4, 'et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui', 222, 0, true, 2, true, true, false, 10);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (64, 30, 6273, false, 2, 2, 1, 1, 1, 8, 8, 4, 2, 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non', 247, 1, true, 0, true, true, true, 6);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (65, 95, 3805, false, 2, 2, 1, 3, 1, 3, 1, 8, 8, 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu', 94, 3, false, 1, false, true, true, 4);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (66, 51, 5626, false, 2, 1, 3, 2, 1, 5, 3, 2, 5, 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', 224, 1, false, 1, false, false, false, 7);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (67, 53, 1045, true, 2, 3, 1, 3, 2, 4, 2, 11, 3, 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum', 90, 3, false, 1, false, false, false, 5);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (68, 51, 3349, false, 1, 1, 2, 1, 1, 8, 7, 11, 7, 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris', 193, 2, true, 0, false, true, false, 13);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (69, 91, 9882, false, 1, 3, 1, 1, 3, 5, 3, 1, 10, 'porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet', 247, 3, false, 1, true, false, false, 8);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (70, 74, 6495, false, 1, 1, 3, 1, 2, 6, 8, 3, 11, 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit', 145, 3, false, 1, true, false, false, 13);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (71, 67, 3796, false, 1, 2, 3, 1, 3, 5, 4, 5, 3, 'quam suspendisse potenti nullam porttitor lacus at turpis donec posuere', 228, 0, false, 1, false, true, false, 15);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (72, 91, 5030, false, 2, 3, 3, 3, 1, 8, 5, 10, 11, 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id', 1, 1, true, 1, false, true, false, 11);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (73, 16, 7287, true, 1, 3, 2, 1, 3, 3, 6, 6, 6, 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis', 62, 2, true, 0, true, true, false, 5);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (74, 21, 2913, false, 1, 3, 2, 2, 2, 3, 5, 1, 9, 'aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet', 234, 0, false, 1, true, true, true, 3);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (75, 41, 2951, true, 2, 3, 3, 1, 2, 2, 7, 2, 1, 'duis faucibus accumsan odio curabitur convallis duis consequat dui nec', 193, 0, false, 2, true, true, true, 10);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (76, 33, 7886, true, 2, 1, 1, 1, 3, 5, 1, 9, 10, 'aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 143, 2, false, 2, false, false, true, 2);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (77, 11, 6332, false, 2, 2, 1, 3, 3, 7, 3, 5, 9, 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut', 142, 3, true, 2, false, true, false, 7);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (78, 82, 765, false, 1, 2, 1, 1, 2, 6, 1, 5, 2, 'condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris', 63, 0, false, 1, true, false, true, 3);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (79, 57, 3622, true, 2, 2, 2, 1, 2, 4, 7, 4, 7, 'sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla', 204, 2, false, 1, true, true, false, 4);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (80, 6, 6777, false, 1, 3, 2, 3, 1, 8, 3, 8, 3, 'proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula', 299, 1, true, 1, true, true, false, 7);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (81, 8, 2178, false, 2, 2, 3, 1, 3, 4, 5, 1, 8, 'libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc', 294, 2, false, 1, false, false, false, 7);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (82, 44, 1315, true, 2, 3, 3, 3, 3, 7, 8, 3, 10, 'duis consequat dui nec nisi volutpat eleifend donec ut dolor', 264, 1, false, 1, true, false, true, 13);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (83, 6, 5849, true, 1, 3, 2, 3, 2, 7, 1, 3, 4, 'vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', 147, 3, false, 1, false, false, false, 1);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (84, 67, 4073, true, 1, 1, 2, 3, 1, 1, 8, 7, 11, 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit', 74, 2, true, 1, true, true, true, 7);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (85, 55, 3346, true, 1, 3, 2, 3, 1, 7, 4, 9, 12, 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam', 180, 1, false, 1, false, true, false, 12);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (86, 47, 4331, false, 2, 3, 3, 2, 1, 3, 4, 12, 10, 'pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate', 72, 2, false, 1, false, false, true, 6);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (87, 62, 4466, false, 2, 3, 3, 3, 1, 1, 3, 1, 12, 'in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum', 69, 3, false, 1, true, true, true, 5);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (88, 5, 713, true, 2, 1, 1, 3, 1, 1, 7, 7, 1, 'nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget', 199, 3, false, 0, true, false, true, 15);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (89, 39, 416, false, 2, 2, 1, 3, 2, 2, 7, 4, 12, 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum', 76, 1, false, 2, true, false, false, 15);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (90, 48, 8530, true, 2, 2, 2, 3, 1, 7, 6, 10, 5, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin', 191, 1, true, 1, false, true, false, 3);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (91, 38, 6500, true, 2, 2, 2, 3, 3, 6, 3, 4, 12, 'morbi ut odio cras mi pede malesuada in imperdiet et', 57, 2, true, 1, false, true, false, 4);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (92, 90, 6710, true, 2, 2, 3, 3, 3, 2, 7, 1, 8, 'condimentum id luctus nec molestie sed justo pellentesque viverra pede', 162, 2, false, 1, false, false, false, 12);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (93, 56, 3177, false, 2, 2, 3, 3, 1, 1, 3, 9, 10, 'lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna', 26, 3, false, 0, false, false, false, 12);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (94, 53, 3788, true, 2, 1, 1, 1, 3, 1, 6, 1, 6, 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus', 206, 2, false, 2, false, true, false, 2);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (95, 5, 5504, true, 1, 3, 3, 1, 3, 1, 2, 1, 9, 'nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', 74, 2, false, 2, true, false, false, 12);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (96, 2, 3288, true, 1, 2, 3, 1, 3, 3, 1, 4, 11, 'dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in', 244, 1, true, 0, false, false, true, 4);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (97, 95, 1814, false, 2, 3, 3, 3, 2, 1, 3, 12, 12, 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum', 117, 0, true, 1, true, true, false, 13);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (98, 85, 4727, false, 2, 3, 1, 3, 2, 4, 2, 2, 8, 'fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales', 47, 0, false, 2, true, true, true, 14);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (99, 19, 7314, false, 2, 2, 2, 2, 1, 8, 2, 10, 1, 'donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in', 251, 0, false, 0, false, true, true, 6);
insert into SCOUTING_FORM (id, match_number, team_number, cross_habitat_line, hab_level_start, sandstorm_cargo_hatch_panel_count, sandstorm_cargo_ball_count, sandstorm_rocket_hatch_panel_count, sandstorm_rocket_ball_count, teleop_cargo_hatch_panel_count, teleop_cargo_ball_count, teleop_rocket_hatch_panel_count, teleop_rocket_ball_count, comment, score, hab_level_climb, defense, preload, buddy_climb, lifted, got_lifted, dropped_game_pieces) values (100, 77, 603, false, 2, 2, 3, 1, 2, 2, 2, 5, 1, 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id', 291, 2, false, 0, true, true, false, 5);