name: CI

on:
  push:
    branches:
      # TODO: Change to master
      - test*

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew build --no-daemon
      - name: Upload api artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: api.jar
          path: api/build/libs/api.jar
      - name: Upload angular artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: scouting-web.zip
          path: scouting-web/build/distributions/scouting-web.zip

  deploy:
    env:
      PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      CLOUDSDK_COMPUTE_REGION: ${{ secrets.CLOUDSDK_COMPUTE_REGION }}
      CLOUDSDK_COMPUTE_ZONE: ${{ secrets.CLOUDSDK_COMPUTE_ZONE }}
      CLOUDSDK_COMPUTE_USER: ${{ secrets.CLOUDSDK_COMPUTE_USER }}
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Download api artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: api.jar
      - name: Download angular artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: scouting-web.zip
      - uses: actions-hub/gcloud@master
        name: GCP list instances
        with:
          args: compute instances list
      - name: GCP copy api jar
        uses: actions-hub/gcloud@master
        with:
          args: compute scp api/build/libs/api.jar $CLOUDSDK_COMPUTE_USER@scouting-test:/scouting/api.jar
      - name: GCP angular zip
        uses: actions-hub/gcloud@master
        with:
          args: compute scp scouting-web/build/distributions/scouting-web.zip $CLOUDSDK_COMPUTE_USER@scouting-test:/scouting/archive.zip
      - name: GCP unzip angular zip
        uses: actions-hub/gcloud@master
        with:
          args: compute ssh $CLOUDSDK_COMPUTE_USER@scouting-test --command "unzip /scouting/archive.zip -d /var/www/html/"
      - name: GCP restart nginx
        uses: actions-hub/gcloud@master
        with:
          args: compute ssh $CLOUDSDK_COMPUTE_USER@scouting-test --command "sudo systemctl restart nginx"
      - name: GCP restart api
        uses: actions-hub/gcloud@master
        with:
          args: compute ssh $CLOUDSDK_COMPUTE_USER@scouting-test --command "sudo systemctl restart api"