name: CI

on:
  push:
    branches:
      # TODO: Change to master
      - test*

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew build --no-daemon
      - uses: actions-hub/gcloud@master
        name: GCP deploy
        env:
          PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: |
            compute instances list
            compute scp api/build/libs/api*.jar scouting-test:/scouting/api.jar
            compute scp scouting-web/build/distributions/scouting-web.zip scouting-test:/scouting/archive.zip
            compute ssh scouting-test --command "unzip /scouting/archive.zip -d /var/www/html/"
            compute ssh scouting-test --command "sudo systemctl restart nginx"
            compute ssh scouting-test --command "sudo systemctl restart api"
