name: CI

on:
  push:
    branches:
      # TODO: Change to master
      - test*

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew build -PdownloadNode=true
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: compute instances list
