name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew build --no-daemon
      - name: Upload api artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: api
          path: api/build/libs/api.jar
      - name: Upload angular artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: angular
          path: scouting-web/build/distributions/scouting-web.zip

  deploy:
    env:
      PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      CLOUDSDK_COMPUTE_REGION: ${{ secrets.CLOUDSDK_COMPUTE_REGION }}
      CLOUDSDK_COMPUTE_ZONE: ${{ secrets.CLOUDSDK_COMPUTE_ZONE }}
      CLOUDSDK_COMPUTE_USER: ${{ secrets.CLOUDSDK_COMPUTE_USER }}
    runs-on: ubuntu-latest
    needs: build
    name: deploy
    steps:
      - name: Download api artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: api
          path: artifacts
      - name: Download angular artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: angular
          path: artifacts
      - name: View artifacts
        run: ls -lah artifacts
      - name: Make api jar executable
        run: chmod +x artifacts/api.jar
      - uses: actions-hub/gcloud@master
        name: GCP list instances
        with:
          args: compute instances list
      - name: GCP upload api jar
        uses: actions-hub/gcloud@master
        with:
          args: compute scp artifacts/api.jar $CLOUDSDK_COMPUTE_USER@scouting:/scouting/api.jar
      - name: GCP upload angular zip
        uses: actions-hub/gcloud@master
        with:
          args: compute scp artifacts/scouting-web.zip $CLOUDSDK_COMPUTE_USER@scouting:/scouting/archive.zip
      - name: GCP unzip angular zip
        uses: actions-hub/gcloud@master
        with:
          args: compute ssh $CLOUDSDK_COMPUTE_USER@scouting --command='sudo unzip -o /scouting/archive.zip -d /var/www/html/'
      - name: GCP restart nginx
        uses: actions-hub/gcloud@master
        with:
          args: compute ssh $CLOUDSDK_COMPUTE_USER@scouting --command='sudo systemctl restart nginx'
      - name: GCP restart api
        uses: actions-hub/gcloud@master
        with:
          args: compute ssh $CLOUDSDK_COMPUTE_USER@scouting --command='sudo systemctl restart api'