name: CI

on:
  push:
    branches:
      # TODO: Change to master
      - test*

env:
  PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
  APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  CLOUDSDK_COMPUTE_REGION: ${{ secrets.CLOUDSDK_COMPUTE_REGION }}
  CLOUDSDK_COMPUTE_ZONE: ${{ secrets.CLOUDSDK_COMPUTE_ZONE }}
  CLOUDSDK_COMPUTE_USER: ${{ secrets.CLOUDSDK_COMPUTE_USER }}
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew build --no-daemon
      - uses: actions-hub/gcloud@master
        name: GCP list instances
        with:
          args: compute instances list
      - uses: actions-hub/gcloud@master
        name: GCP copy api jar
        with:
          args: compute scp api/build/libs/api*.jar $CLOUDSDK_COMPUTE_USER@scouting-test:/scouting/api.jar
      - uses: actions-hub/gcloud@master
        name: GCP angular zip
        with:
          args: compute scp scouting-web/build/distributions/scouting-web.zip $CLOUDSDK_COMPUTE_USER@scouting-test:/scouting/archive.zip
      - uses: actions-hub/gcloud@master
        name: GCP unzip angular zip
        with:
          args: compute ssh $CLOUDSDK_COMPUTE_USER@scouting-test --command "unzip /scouting/archive.zip -d /var/www/html/"
      - uses: actions-hub/gcloud@master
        name: GCP restart nginx
        with:
          args: compute ssh $CLOUDSDK_COMPUTE_USER@scouting-test --command "sudo systemctl restart nginx"
      - uses: actions-hub/gcloud@master
        name: GCP restart api
        with:
          args: compute ssh $CLOUDSDK_COMPUTE_USER@scouting-test --command "sudo systemctl restart api"